# Generated by Django 3.1.4 on 2021-01-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210103_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='currency',
        ),
        migrations.AddField(
            model_name='account',
            name='_currency',
            field=models.CharField(choices=[('USD', 'United States dollar'), ('RUB', 'Russian Ruble'), ('KZT', 'Tenge'), ('BTC', 'Bitcoin'), ('LTC', 'Litecoin')], default='USD', max_length=3),
        ),
    ]
